<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Departments Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 20px; font-size: 12px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #333; padding-bottom: 20px; }
        .company-info { margin-bottom: 20px; }
        .company-name { font-size: 24px; font-weight: bold; color: #333; margin-bottom: 5px; }
        .company-details { font-size: 12px; color: #666; }
        .title-box { background-color: #f8f9fa; border: 1px solid #dee2e6; padding: 15px; text-align: center; margin: 20px 0; }
        .report-title { font-size: 18px; font-weight: bold; color: #333; margin: 0; }
        .report-date { font-size: 12px; color: #666; margin-top: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; font-size: 11px; }
        td { font-size: 11px; }
        .status-active { color: #28a745; font-weight: bold; }
        .status-inactive { color: #dc3545; font-weight: bold; }
        .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #666; border-top: 1px solid #ddd; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-info">
            @if($companySetting && $companySetting->logo)
                <img src="{{ public_path('storage/' . $companySetting->logo) }}" alt="Company Logo" style="height: 60px; margin-bottom: 10px;">
            @endif
            <div class="company-name">{{ $companySetting->company_name ?? 'Company Name' }}</div>
            <div class="company-details">
                @if($companySetting)
                    {{ $companySetting->address }}<br>
                    Phone: {{ $companySetting->phone }} | Email: {{ $companySetting->email }}
                @endif
            </div>
        </div>
        
        <div class="title-box">
            <h1 class="report-title">Employee Departments Report</h1>
            <div class="report-date">Generated on: {{ date('F d, Y') }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 10%;">#</th>
                <th style="width: 40%;">Department Name</th>
                <th style="width: 30%;">Employee Type</th>
                <th style="width: 20%;">Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($departments as $index => $department)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $department->name }}</td>
                    <td>{{ $department->empType?->name ?? 'No Type' }}</td>
                    <td class="{{ $department->status ? 'status-active' : 'status-inactive' }}">
                        {{ $department->status ? 'Active' : 'Inactive' }}
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; padding: 20px; color: #666;">
                        No departments found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report contains {{ $departments->count() }} department(s) | Generated by {{ $companySetting->company_name ?? 'System' }}</p>
    </div>
</body>
</html>